package clinica;

import vistas.UsuarioIF;
import vistas.PacienteIF;
import vistas.MedicoIF;
import vistas.EspecialidadIF;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.Dimension;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;

/**
 *
 * @author Pablo Hurtado
 */
public final class Clinica extends javax.swing.JFrame {
    
    
    public Clinica() {
        initComponents();
        setContentPane(Escritorio);
        Escritorio.setBackground(new java.awt.Color(0,128,192));
        this.setVisible(false);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    public void centerJIF(JInternalFrame jif) {
        Dimension desktopSize = Escritorio.getSize();
        Dimension jInternalFrameSize = jif.getSize();
        int width = (desktopSize.width - jInternalFrameSize.width) / 2;
        int height = (desktopSize.height - jInternalFrameSize.height) / 2;
        jif.setLocation(width, height);
        jif.setVisible(true);
    }
    
    public boolean validar(JInternalFrame jif){
        boolean estado;
        estado = jif.isClosed();
        return estado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JSeparator();
        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnuPrArchivo = new javax.swing.JMenu();
        MnuSalir = new javax.swing.JMenuItem();
        MnuPrOperaciones = new javax.swing.JMenu();
        MnuPrCatalogo = new javax.swing.JMenu();
        MnuEstudiantes = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        MnuTipomedico = new javax.swing.JMenuItem();
        MnuUniversidades = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        MnuPrReportes = new javax.swing.JMenu();
        MnuPrUtilitarios = new javax.swing.JMenu();
        MnuPrAyuda = new javax.swing.JMenu();

        jMenuItem5.setText("jMenuItem5");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MnuPrArchivo.setMnemonic('A');
        MnuPrArchivo.setText("Archivo");

        MnuSalir.setMnemonic('s');
        MnuSalir.setText("Salir");
        MnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuSalirActionPerformed(evt);
            }
        });
        MnuPrArchivo.add(MnuSalir);

        jMenuBar1.add(MnuPrArchivo);

        MnuPrOperaciones.setMnemonic('o');
        MnuPrOperaciones.setText("Registros");
        jMenuBar1.add(MnuPrOperaciones);

        MnuPrCatalogo.setMnemonic('c');
        MnuPrCatalogo.setText("Catálogos");

        MnuEstudiantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/enfermera.png"))); // NOI18N
        MnuEstudiantes.setMnemonic('e');
        MnuEstudiantes.setText("Pacientes");
        MnuEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuEstudiantesActionPerformed(evt);
            }
        });
        MnuPrCatalogo.add(MnuEstudiantes);
        MnuPrCatalogo.add(jSeparator2);

        MnuTipomedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/doctor.png"))); // NOI18N
        MnuTipomedico.setMnemonic('p');
        MnuTipomedico.setText("Medico");
        MnuTipomedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuTipomedicoActionPerformed(evt);
            }
        });
        MnuPrCatalogo.add(MnuTipomedico);

        MnuUniversidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/farmacia.png"))); // NOI18N
        MnuUniversidades.setMnemonic('u');
        MnuUniversidades.setText("Especialidad");
        MnuUniversidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuUniversidadesActionPerformed(evt);
            }
        });
        MnuPrCatalogo.add(MnuUniversidades);
        MnuPrCatalogo.add(jSeparator3);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/grupo.png"))); // NOI18N
        jMenuItem1.setMnemonic('d');
        jMenuItem1.setText("Usuario");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MnuPrCatalogo.add(jMenuItem1);

        jMenuBar1.add(MnuPrCatalogo);

        MnuPrReportes.setMnemonic('r');
        MnuPrReportes.setText("Reportes");
        jMenuBar1.add(MnuPrReportes);

        MnuPrUtilitarios.setMnemonic('u');
        MnuPrUtilitarios.setText("Utilitarios");
        jMenuBar1.add(MnuPrUtilitarios);

        MnuPrAyuda.setMnemonic('y');
        MnuPrAyuda.setText("Ayuda");
        jMenuBar1.add(MnuPrAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnuTipomedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuTipomedicoActionPerformed
        MedicoIF medicoVent = new MedicoIF();
        centerJIF(medicoVent);
        Escritorio.add(medicoVent);
        medicoVent.toFront();
        try {
            medicoVent.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Clinica.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_MnuTipomedicoActionPerformed

    private void MnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuSalirActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "Desea Salir?","Confirmar",
                JOptionPane.OK_CANCEL_OPTION,JOptionPane.ERROR_MESSAGE);
        if(i==JOptionPane.OK_OPTION){
            System.exit(0);}
    }//GEN-LAST:event_MnuSalirActionPerformed

    private void MnuUniversidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuUniversidadesActionPerformed
        EspecialidadIF universidadVent = new EspecialidadIF();
        centerJIF(universidadVent);
        Escritorio.add(universidadVent);
        universidadVent.toFront();
        try {
            universidadVent.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Clinica.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MnuUniversidadesActionPerformed

    private void MnuEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuEstudiantesActionPerformed
        PacienteIF estudianteVent = new PacienteIF();
        centerJIF(estudianteVent);
        Escritorio.add(estudianteVent);
        estudianteVent.toFront();
        try {
            estudianteVent.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Clinica.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MnuEstudiantesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        UsuarioIF  docenteVent = new UsuarioIF();
        centerJIF(docenteVent);
        Escritorio.add(docenteVent);
        docenteVent.toFront();
        try {
            docenteVent.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Clinica.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem MnuEstudiantes;
    private javax.swing.JMenu MnuPrArchivo;
    private javax.swing.JMenu MnuPrAyuda;
    private javax.swing.JMenu MnuPrCatalogo;
    private javax.swing.JMenu MnuPrOperaciones;
    private javax.swing.JMenu MnuPrReportes;
    private javax.swing.JMenu MnuPrUtilitarios;
    private javax.swing.JMenuItem MnuSalir;
    private javax.swing.JMenuItem MnuTipomedico;
    private javax.swing.JMenuItem MnuUniversidades;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
