package clinica;

import vistas.UsuarioIF;
import vistas.PacienteIF;
import vistas.MedicoIF;
import vistas.EspecialidadIF;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.Dimension;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import vistas.HistorialClinicoIF;

/**
 *
 * @author Pablo Hurtado
 */
public final class Clinica extends javax.swing.JFrame {
    
    
    public Clinica() {
        initComponents();
        setContentPane(Escritorio);
        Escritorio.setBackground(new java.awt.Color(0,128,192));
        this.setVisible(false);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    public void centerJIF(JInternalFrame jif) {
        Dimension desktopSize = Escritorio.getSize();
        Dimension jInternalFrameSize = jif.getSize();
        int width = (desktopSize.width - jInternalFrameSize.width) / 2;
        int height = (desktopSize.height - jInternalFrameSize.height) / 2;
        jif.setLocation(width, height);
        jif.setVisible(true);
    }
    
    public boolean validar(JInternalFrame jif){
        boolean estado;
        estado = jif.isClosed();
        return estado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JSeparator();
        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnuPrArchivo = new javax.swing.JMenu();
        MnuSalir = new javax.swing.JMenuItem();
        MnuPrCatalogo = new javax.swing.JMenu();
        mnuHistorial = new javax.swing.JMenuItem();
        MnuPacientes = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        MnuMedico = new javax.swing.JMenuItem();
        MnuEspecialidad = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnuUsuario = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        MnuPrArchivo.setMnemonic('A');
        MnuPrArchivo.setText("Archivo");
        MnuPrArchivo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        MnuSalir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        MnuSalir.setMnemonic('s');
        MnuSalir.setText("Salir");
        MnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuSalirActionPerformed(evt);
            }
        });
        MnuPrArchivo.add(MnuSalir);

        jMenuBar1.add(MnuPrArchivo);

        MnuPrCatalogo.setMnemonic('c');
        MnuPrCatalogo.setText("Catálogos");
        MnuPrCatalogo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        mnuHistorial.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        mnuHistorial.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        mnuHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/notepad.png"))); // NOI18N
        mnuHistorial.setText("Historial");
        mnuHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHistorialActionPerformed(evt);
            }
        });
        MnuPrCatalogo.add(mnuHistorial);

        MnuPacientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        MnuPacientes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        MnuPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/enfermera.png"))); // NOI18N
        MnuPacientes.setMnemonic('e');
        MnuPacientes.setText("Pacientes");
        MnuPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuPacientesActionPerformed(evt);
            }
        });
        MnuPrCatalogo.add(MnuPacientes);
        MnuPrCatalogo.add(jSeparator2);

        MnuMedico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        MnuMedico.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        MnuMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/doctor.png"))); // NOI18N
        MnuMedico.setMnemonic('p');
        MnuMedico.setText("Medico");
        MnuMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuMedicoActionPerformed(evt);
            }
        });
        MnuPrCatalogo.add(MnuMedico);

        MnuEspecialidad.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        MnuEspecialidad.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        MnuEspecialidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/farmacia.png"))); // NOI18N
        MnuEspecialidad.setMnemonic('u');
        MnuEspecialidad.setText("Especialidad");
        MnuEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuEspecialidadActionPerformed(evt);
            }
        });
        MnuPrCatalogo.add(MnuEspecialidad);
        MnuPrCatalogo.add(jSeparator3);

        mnuUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        mnuUsuario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        mnuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/grupo.png"))); // NOI18N
        mnuUsuario.setMnemonic('d');
        mnuUsuario.setText("Usuario");
        mnuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUsuarioActionPerformed(evt);
            }
        });
        MnuPrCatalogo.add(mnuUsuario);

        jMenuBar1.add(MnuPrCatalogo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnuMedicoActionPerformed(java.awt.event.ActionEvent evt) {                                              
        MedicoIF medicoVent = new MedicoIF();
        centerJIF(medicoVent);
        Escritorio.add(medicoVent);
        medicoVent.toFront();
        try {
            medicoVent.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Clinica.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }                                         

    private void MnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuSalirActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "Desea Salir?","Confirmar",
                JOptionPane.OK_CANCEL_OPTION,JOptionPane.ERROR_MESSAGE);
        if(i==JOptionPane.OK_OPTION){
            System.exit(0);}
    }//GEN-LAST:event_MnuSalirActionPerformed

    private void MnuEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuEspecialidadActionPerformed
        EspecialidadIF especialidadVent = new EspecialidadIF();
        centerJIF(especialidadVent);
        Escritorio.add(especialidadVent);
        especialidadVent.toFront();
        try {
            especialidadVent.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Clinica.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MnuEspecialidadActionPerformed

    private void MnuPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuPacientesActionPerformed
        PacienteIF pacienteVent = new PacienteIF();
        centerJIF(pacienteVent);
        Escritorio.add(pacienteVent);
        pacienteVent.toFront();
        try {
            pacienteVent.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Clinica.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MnuPacientesActionPerformed

    private void mnuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUsuarioActionPerformed
        UsuarioIF  usuarioVent = new UsuarioIF();
        centerJIF(usuarioVent);
        Escritorio.add(usuarioVent);
        usuarioVent.toFront();
        try {
            usuarioVent.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Clinica.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnuUsuarioActionPerformed

    private void mnuHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHistorialActionPerformed
        HistorialClinicoIF historialVent = new HistorialClinicoIF();
        centerJIF(historialVent);
        Escritorio.add(historialVent);
        historialVent.toFront();
        try {
            historialVent.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Clinica.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_mnuHistorialActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem MnuEspecialidad;
    private javax.swing.JMenuItem MnuMedico;
    private javax.swing.JMenuItem MnuPacientes;
    private javax.swing.JMenu MnuPrArchivo;
    private javax.swing.JMenu MnuPrCatalogo;
    private javax.swing.JMenuItem MnuSalir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JMenuItem mnuHistorial;
    private javax.swing.JMenuItem mnuUsuario;
    // End of variables declaration//GEN-END:variables
}
